### ISSUE TITLE
Знайти фото Новороздільського політехнічного фахового коледжу в Інтернеті

### ISSUE THREAD

**Issue by halchyhaaa** [halchyhaaa/pr4_2021#1]
ВИБРАТИ НАЙКРАЩЕ ФОТО

**Comment by ahalko29** [comment]
фото НРПФК

**Comment by ahalko29** [comment]
![image](https://user-images.githubusercontent.com/94022381/141029937-b171b478-fe58-4ac1-9f0b-23655bd5e8a9.png)

**Comment by ahalko29** [comment]
Зображення знайдено

**Comment by ahalko29** [comment]
!!
